plugins: ['jekyll/scholar']

scholar:
  group_by: year
  group_order: descending
  bibliography_group_tag: 'h3,h4,h5,h6'
  bibliography_list_tag: 'ul'
  bibliography_template: reference

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
